# Generated by Django 5.2.8 on 2025-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Model', models.CharField(max_length=1)),
                ('Date_of_Manufacture', models.DateTimeField()),
                ('Reviews', models.IntegerField()),
                ('Colour', models.CharField(max_length=30)),
            ],
        ),
    ]
